#nginxを使用
FROM nginx:alpine

#nginxの設定ファイルコピー
COPY nginx.conf /etc/nginx/conf.d/default.conf

#ビルド成果物をコピー
COPY --from=gomoku /build /usr/share/nginx/html

#ポート番号を公開
EXPOSE 80

#nginxをフォアグラウンドで起動
CMD [ "nginx", "-g","deamon off;" ]