#nudoのバージョンを18に変更
FROM node:18-alpine

#appディレクトリを作成
WORKDIR /app

#package.json package-lock.jsonをコピー
COPY package.json package-lock.json ./

#必要なパッケージをインストールする
RUN npm install

#ソースコードをコピーする
COPY . .

#appをビルド
RUN npm run build

#dockerファイルのポート番号を3000に設定
EXPOSE 3000

#アプリケーションの起動
CMD ["npm", "start"]
