#nginxを使用
FROM nginx:18-alpine

#ディレクトリの作成
WORKDIR /app

#package.json package-lock.jsonのコピー
COPY package.json package-lock.json ./

#node_modulesをインストール
RUN npm install

#ソースコードをコピー
COPY  . .

#ビルド
RUN npm run build